<?php

namespace AppBundle\Repository;

/**
 * CambioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CambioRepository extends \Doctrine\ORM\EntityRepository
{
}
