<?php

namespace AppBundle\Repository;

/**
 * FFijaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FFijaRepository extends \Doctrine\ORM\EntityRepository
{
}
