<?php

namespace AppBundle\Repository;

/**
 * JugadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JugadorRepository extends \Doctrine\ORM\EntityRepository
{
}
