<?php

namespace AppBundle\Repository;

/**
 * PartidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartidoRepository extends \Doctrine\ORM\EntityRepository
{
}
