<?php

namespace AppBundle\Repository;

/**
 * ScrumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScrumRepository extends \Doctrine\ORM\EntityRepository
{
}
