<?php

namespace AppBundle\Repository;

/**
 * TackleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TackleRepository extends \Doctrine\ORM\EntityRepository
{
}
